version: '3.8'

services:
  api:
    build: .
    command: gunicorn -w 1 -b 0.0.0.0:5000 "api.app:create_app()"
    ports:
      - 5000:5000
    depends_on:
      - fluent-bit
    logging:
      # используемый драйвер логгирования
      driver: "fluentd"
      options:
        # куда посылать лог-сообщения, необходимо что бы адрес
        # совпадал с настройками плагина forward
        fluentd-address: localhost:24224
        # теги используются для маршрутизации лог-сообщений
        tag: api.logs

  elasticsearch:
    image: elasticsearch:8.3.2
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      xpack.security.enabled: false
      discovery.type: single-node
      cluster.name: logs-cluster
      network.host: localhost

  kibana:
    image: kibana:8.3.2
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch

  fluent-bit:
    image: fluent/fluent-bit
    ports:
      # необходимо открыть порты, которые используются плагином forward
      - 24224:24224
      - 24224:24224/udp
    volumes:
      # добавляем конфигурацию в контейнер
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit/parsers.conf:/fluent-bit/parsers/parsers.conf

volumes:
  elasticsearch_data: