version: '3.8'

services:
  test-api:
    build: .
    ports:
      - XXXX:YYYY
    depends_on:
      - fluent-bit
    logging:
      # используемый драйвер логгирования
      driver: "fluentd"
      options:
        # куда посылать лог-сообщения, необходимо что бы адрес
        # совпадал с настройками плагина forward
        fluentd-address: localhost:24234
        # теги используются для маршрутизации лог-сообщений
        tag: api.logs

  elasticsearch:
    image: elasticsearch:8.3.2
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      xpack.security.enabled: false
      discovery.type: single-node
      cluster.name: logs-cluster
      network.host: localhost

  kibana:
    image: kibana:8.3.2
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://test-elasticsearch:9200
    depends_on:
      - elasticsearch


volumes:
  elasticsearch:
